#!/usr/bin/env bash
set -euo pipefail

INSTALL_DIR="${SCREENBRIEF_INSTALL_DIR:-$HOME/.agents/skills/screenbrief}"
PURGE=false
TIMESTAMP="$(date +%Y%m%d-%H%M%S)"

usage() {
  cat <<'USAGE'
Usage: bash uninstall.sh [options]

Options:
  --purge    Delete the installed skill directory instead of moving it to a backup path.
  -h, --help Show this help.
USAGE
}

log() {
  printf '[screenbrief] %s\n' "$*"
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --purge)
      PURGE=true
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
  shift
done

remove_symlink_if_points_to_install() {
  local link_path="$1"
  if [ ! -L "$link_path" ]; then
    return
  fi

  local target
  target="$(readlink "$link_path")"
  if [ "$target" = "$INSTALL_DIR" ]; then
    rm "$link_path"
    log "Removed symlink: $link_path"
  else
    log "Skipped symlink with different target: $link_path -> $target"
  fi
}

remove_cli_wrapper() {
  local wrapper="$HOME/.local/bin/screenbrief"
  if [ ! -e "$wrapper" ] && [ ! -L "$wrapper" ]; then
    return
  fi

  if grep -q "Generated by ScreenBrief installer" "$wrapper" 2>/dev/null; then
    rm "$wrapper"
    log "Removed CLI wrapper: $wrapper"
  else
    log "Skipped non-ScreenBrief CLI wrapper: $wrapper"
  fi
}

remove_symlink_if_points_to_install "$HOME/.codex/skills/screenbrief"
remove_symlink_if_points_to_install "$HOME/.claude/skills/screenbrief"
remove_cli_wrapper

if [ -d "$INSTALL_DIR" ] || [ -L "$INSTALL_DIR" ]; then
  if [ "$PURGE" = true ]; then
    rm -rf "$INSTALL_DIR"
    log "Deleted installed skill directory: $INSTALL_DIR"
  else
    backup_path="${INSTALL_DIR}.removed-${TIMESTAMP}"
    mv "$INSTALL_DIR" "$backup_path"
    log "Moved installed skill directory to: $backup_path"
  fi
fi

log "Uninstall complete."
